portfolio_env/urls.py
from django.conf.urls import *
from django.conf import settings
from myapp import views
from django.contrib import admin
from django.views.generic.base import RedirectView


from myapp.views import *

urlpatterns = [

	url(r'^admin/', include(admin.site.urls)),
	url(r'^$', views.home_page, name='home'),
	url(r'^photos_of_$', views.user_photos, name='flickr_api'),
	url(r'^maze$', views.maze, name='maze'),
	url(r'^stack$', views.stack),
	url(r'^USD-BTC_exchange_rate', views.current_exchange_rate, name='current_exchange_rate'),
	url(r'^contact', views.contact_view, name='contact'),
	url(r'^get_best_rate', views.get_best_rate, name='get_best_rate'),

]

myapp/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class Bet_USD_BTC(models.Model):

	time = models.DateTimeField()
	highest_bid = models.DecimalField(max_digits=19, decimal_places=6)
	h_bid_stack = models.CharField(max_length=30)
	lowest_ask = models.DecimalField(max_digits=19, decimal_places=6)
	l_ask_stack = models.CharField(max_length=30)
	spread = models.DecimalField(max_digits=19, decimal_places=6)
	nice_spread = models.BooleanField(default=False)

myapp/forms.py
from __future__ import unicode_literals

from django import forms
from datetime import datetime

class ContactForm(forms.Form):
	
	subject = forms.CharField(max_length=100, widget = forms.TextInput(attrs = {'class': 'form-control theme', 'required': 'True', 'help_text': '100 characters max.'}))
	sender = forms.EmailField(max_length=254, widget=forms.EmailInput(attrs={'class': 'contact-form'}))
	message = forms.CharField(max_length=1000)

myapp/views.py
#!/usr/local/bin/python3.5
# -*- coding: utf-8 -*-

# Create your views here.
import os, sys
import requests, json, base64
import textwrap
import math, time, datetime, random
import django.shortcuts
from django.shortcuts import render_to_response, redirect
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.http import HttpResponse, Http404
from django.views.generic.base import View
from django.template import Template, Context, loader, RequestContext
from django.template.loader import get_template
from django.template.response import TemplateResponse
from django.template.defaulttags import register
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.models import User
from django.db import connection
from .models import *
from .forms import *
from fractions import Fraction

URL_BASE = 'https://api.flickr.com/services/rest/?'
API_KEY = 'a2a7084e3f260f580e687bc7a65c6b75'
FORMAT = 'json'
NOJSONCALLBACK = '1'
BASIC_REQUEST = (URL_BASE + 'api_key=' + API_KEY + '&format=' + FORMAT + '&nojsoncallback=' + NOJSONCALLBACK + '&method=')


def handler404(request):
    return TemplateResponse(request, '404.html')
    response.status_code = 404

def handler500(request):
    return TemplateResponse(request, '50x.html')
    response.status_code = 500

def user_photos(request):

  urlname = request.GET['username']
  profile_url = 'https://www.flickr.com/photos/' + urlname

  upper_text = 'Impossible considered invitation him men instrument saw celebrated unpleasant. \
  Put rest and must set kind next many near nay. He exquisite continued explained middleton am. \
  Voice hours young woody has she think equal. Estate moment he at on wonder at season little. \
  Six garden result summer set family esteem nay estate. End admiration mrs unreserved discovered comparison especially invitation.'
  above_text = '<p>Able an hope of body. Any nay shyness article matters own removal nothing his forming. \
  Gay own additions education satisfied the perpetual. If he cause manor happy. Without farther she exposed \
  saw man led. Along on happy could cease green oh. </p><p>Betrayed cheerful declared end and. Questions we \
  additions is extremely incommode. Next half add call them eat face. Age lived smile six defer bed their few. \
  Had admitting concluded too behaviour him she. Of death to or to being other. </p></div><div class="col-sm-6">\
  <p>Effects present letters inquiry no an removed or friends. Desire behind latter me though in. Supposing shameless \
  am he engrossed up additions. My possible peculiar together to. Desire so better am cannot he up before points. \
  Remember mistaken opinions it pleasure of debating. Court front maids forty if aware their at. Chicken use are pressed \
  removed. </p><p>Saw yet kindness too replying whatever marianne. Old sentiments resolution admiration unaffected its \
  mrs literature. Behaviour new set existence dashwoods. It satisfied to mr commanded consisted disposing engrossed. \
  Tall snug do of till on easy. Form not calm new fail. </p>'

  if 'p' not in request.GET:
    p = 1
  elif 'p' in request.GET:
    p = int(request.GET['p'])
  current_page = p
  next_page = current_page + 1
  prev_page = current_page - 1

  photo_list = []
  paginator = []


  method = 'flickr.urls.lookupUser'
  extra_param = ('&url=' + profile_url)

  user_id_request = (BASIC_REQUEST + method + extra_param)

  json_obj = requests.get(user_id_request)
  resp = json_obj.json()


  if resp['stat'] == 'fail': # There is no user with such name
    short_descr = 'There is no such user on Flickr'
    real_name = 'We know nothing about him'
    portfolio = ''
    userpic = '<img src="https://s.yimg.com/pw/images/buddyicon.jpg" alt="" class="img-responsive img-circle">'
    upper_text = ''
  
  elif resp['stat'] == 'ok': # There is a user with such name
    user = resp['user']
    user_id = user['id']
    username_stat = user['username']
    short_descr = 'About ' + urlname

    method = 'flickr.people.getInfo'
    extra_param = ('&user_id=' + user_id)

    user_info_request = ( BASIC_REQUEST + method + extra_param)

    json_obj = requests.get(user_info_request)
    resp = json_obj.json()

    person = resp['person']
    iconserver = str(person['iconserver'])
    iconfarm = str(person['iconfarm'])
    try:
      cont = person['realname']
      real_name = cont['_content']
    except KeyError:
      real_name = urlname
    
    text = ''

    method = 'flickr.people.getPublicPhotos'
    extra_param = ('&user_id=' + user_id + 
                  '&per_page=' + '60' + 
                  '&page=' + str(p)
                  )

    photo_info_request = (BASIC_REQUEST + method + extra_param)

    json_obj = requests.get(photo_info_request)
    resp = json_obj.json()

    photos = resp['photos']
    photo = photos['photo']
    pages = int(photos['pages'])


    if len(photo) == 0: # No public photos
      text = text + '<p>' + urlname + ' has no public photos yet</p>'

    else:

      for item in photo:
        farm = str(item['farm'])
        server = str(item['server'])
        photo_id = str(item['id'])
        secret = str(item['secret'])
        title = str(item['title'])
        if title == '':
          title = '--no name--'

        photo_list.append('<div class="col-sm-2"><div class="box"><a href="https://farm' + farm + '.staticflickr.com/' + server + \
          '/' + photo_id + '_' + secret + '_z.jpg" alt="' + title + '" data-toggle="lightbox" data-gallery="portfolio" data-title="' + \
          title + '" data-footer="Some footer information"><img src="https://farm' + farm + '.staticflickr.com/' + server + '/' + photo_id + '_' + secret + '_q.jpg" \
          alt="" class="img-responsive"></a></div></div>')

      if pages > 1:

        paginator.append('<hr>\n    <div class="row text-center">\n     <div class="col-lg-12">\n      <ul class="pagination">\n       ')

        for page in range(1, pages+1):
          if page == current_page:
            paginator.append('       <li class="active">\n        <a href="/photos_of_?username=' + urlname + '&p=' + str(current_page) + '">' + str(current_page) + '</a>\n       </li>\n')
          else:
            paginator.append('       <li>\n        <a href="photos_of_?username=' + urlname + '&p=' + str(page) + '">' + str(page) + '</a>\n       </li>')       
        
        paginator.append('      </ul>\n     </div>\n    </div>\n')                

    userpic = '<img src="https://farm' + iconfarm + '.staticflickr.com/' + iconserver + '/buddyicons/' + user_id + '_r.jpg" alt="" class="img-responsive img-circle">'''
  t = get_template('photos_templ_bootstrap.html')
  html = t.render(Context({'userpic': userpic, 'upper_text': upper_text, 'above_text': above_text, 'short_descr': short_descr, 'about': real_name, 'username': urlname, 'photos': '\n'.join(photo_list), 'paginator': ''.join(paginator)}))
  del photo_list[:]
  del paginator[:]
  

  return HttpResponse(html)

def home_page(request):
  t = get_template('home_templ.html')
  html = t.render(Context())
  return HttpResponse(html)


@csrf_exempt
def contact_view(request):
  form = ContactForm()
  if request.method == 'POST':
    form = ContactForm(request.POST)
    # Если форма заполнена корректно, сохраняем все введённые пользователем значения
    if form.is_valid():
      subject = form.cleaned_data['subject']
      sender = form.cleaned_data['sender']
      message = form.cleaned_data['message']

      recepients = ['antoninacurafina@gmail.com']
      try:
          send_mail(subject, message, sender, recepients)
          return TemplateResponse(request, 'mail_sent.html')
      except BadHeaderError: #Защита от уязвимости
          return HttpResponse('Invalid header found')
      # Переходим на другую страницу, если сообщение отправлено
      return TemplateResponse(request, 'mail_sent.html')

    else:
        form = ContactForm()
  # Выводим форму в шаблон
  return TemplateResponse(request, 'contact.html', {'form': form, 'username': ''})


def maze(request):

  # количество клеток/ходов в высоту и ширину, задаются пользователем
  w = 0
  h = 0

  # длина стороны квадратной комнаты и ширина стенки (длина=длине комнаты), также есть в стилях шаблона
  room_width = 30
  wall_width = 10
  cell_width = room_width + wall_width

  # тут может быть любой набор символов, но с такими лабиринт нагляден даже в качестве построчного вывода массива
  space = ' '
  full = '*'
  line_hor = '_'
  line_ver = '|'

  maze = []
  pure_path = [] #список всех ходов без учета выбирания из тупиков
  keychain = [] #список всех ходов с учетом выбирания из тупиков (ходы, приводящие в тупики, убираются после выхода из тупика)


  #проверка на тупик (отсутствие ходов из данной позиции)
  def check_dead_end(maze, height, width, x, y):
    if (x == height-2 or maze[x+2][y] == space) and (y == width-2 or maze[x][y+2] == space) and (x == 1 or maze[x-2][y] == space) and (y == 1 or maze[x][y-2] == space):
      return 'yes'
    else:
      return 'no'

  if 'h' in request.GET and 'w' in request.GET:
    h = int(request.GET['h'])
    w = int(request.GET['w'])
    if h > 0 and w > 0:

      
      # по два символа на клетку (три подряд клетки выглядят так: |_|_|_) плюс доп. клетка в высоту и ширину (от нее оставим только стенку)
      height = h * 2 + 1
      width = w * 2 + 1
      h_px = str(h * cell_width + wall_width)+'px'
      w_px = str(w * cell_width + wall_width)+'px'

      # строим непройденный дабиринт, есть стенки клетка состоит из заполнение + 3/6 стенок, + доп. стенки для замыкающих клеток
      maze = [[line_ver, full] * (w+1) for q in range(height)]
      walls = [[line_hor, line_hor] * (w+1) for q in range(height)]

      for q in range(0, height, 2):
        maze[q] = walls[q]

      for q in range(height):
        del maze[q][-1]
        maze[q][0] = maze[q][-1] = line_ver

myapp/templates/50x.html
<!DOCTYPE html>

	<link rel="shortcut icon" type="image/png" href="/static/img/favicon.ico"/>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="error404">
	<meta name="author" content="lapantonina">

	<title>Internal Server Error</title>

	<!-- Bootstrap Core CSS -->
	<link href="/static/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="/static/css/custom.css" rel="stylesheet">
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<ul class="nav navbar-nav">
				<li><a href="..">Home</a></li>
				<li><a href="../contact">Contact form</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<div class="container wrapper">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
		 			<p class="lead">The server encountered an internal error or misconfiguration and was unable to complete your request.</p>
		 			<p><a href="..">Go to the homepage</a></p>
		 			<img class="img-responsive" src="/static/img/zhevuzador.jpg" alt="error404">
				</div>
			</div>
		</div>

	<footer style="background-color: #333333;" class="section-inverse">
		<div class="container"> 
			<div class="row copyright">
				<div class="col-md-6">
					<p>&copy;2017 Loutique</p>
				</div>
				<div class="col-md-6">
					<p class="credit">Template by <a href="http://bootstrapious.com/landing-pages">Bootstrapious &mdash; Bootstrap Landing Pages</a></p>
				<!-- Please do not remove the backlink to us. It is part of the licence conditions. Thanks for understanding :)-->
				</div>
			</div>
		</div>
	</footer>

<!-- jQuery -->
  <script src="/static/js/jquery-1.11.0.min.js"></script>
  <script src="/static/js/bootbox.min.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="/static/js/bootstrap.min.js"></script>
		
</body>
</html>

myapp/templates/USD-BTC_exchange_rate.html
<!DOCTYPE html>
<head>
  <link rel="shortcut icon" type="image/png" href="/static/img/favicon.ico"/>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="maze_generator">
  <meta name="author" content="lapantonina">
  
  <title>USD/BTC Exchange Rate</title>  
  <!-- Bootstrap Core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom CSS -->
  <link href="/static/css/custom.css" rel="stylesheet">


<style>

.label-box ul li {
  display: inline;
  position: relative;
  padding: 2px 50px 2px 25px;
  margin-left: -40px;
  
}
.label-box li span {
  display: block;
  position: absolute;
  left: 0;
  top: 0;
  width: 20px;
  height: 100%;
  border-radius: 5px;
}


.form-control[readonly] {
    cursor: auto;
    margin-bottom: 12px;
}

h4 {
  margin-bottom: 20px;
}
</style>

</head>

<body data-spy="scroll" data-target="#navigation" data-offset="120">

<script src="/static/js/charts.js"></script>
<script type="text/javascript">

  let previous_data = {% autoescape off %}{{ previous_data }}{% endautoescape %};
  window.onload = function () {
    let canvas = document.getElementById('updating-chart'),
      ctx = canvas.getContext('2d'),
      startingData = {
        date: previous_data[0],
        labels: previous_data[1],
        spread: previous_data[6],
        datasets: [
            {
                label: 'highest_bid',
                fillColor: "rgba(133,187,0,0.2)",
                strokeColor: "rgba(133,187,0,1)",
                pointColor: "rgba(133,187,0,1)",
                pointStrokeColor: "#fff",
                data: previous_data[2],
                h_bid_stack: previous_data[3],
            },
            {
                label: 'lowest_ask',
                fillColor: "rgba(199,87,37,0.1)",
                strokeColor: "rgba(199,87,37,1)",
                pointColor: "rgba(199,87,37,1)",
                pointStrokeColor: "#fff",
                data: previous_data[4],
                l_ask_stack: previous_data[5], 
            }
        ],
        
      },
      date = startingData.date[24];
      latestLabel = startingData.labels[24];
      lowest_ask = startingData.datasets[1]['data'][24];
      l_ask_stack = startingData.datasets[1]['l_ask_stack'][24];
      highest_bid = startingData.datasets[0]['data'][24];
      h_bid_stack = startingData.datasets[0]['h_bid_stack'][24];
      spread = startingData.spread[24];
      document.getElementById("time").value = `${date}, ${latestLabel}`;
      document.getElementById("lowest_ask").value = `${lowest_ask} (${l_ask_stack})`;
      document.getElementById("highest_bid").value = `${highest_bid} (${h_bid_stack})`;
      document.getElementById("spread").value = `\$${spread}`;

  let myLiveChart = new Chart(ctx).Line(startingData, {animationSteps: 20});
  document.getElementById("legend").innerHTML = myLiveChart.generateLegend();
  setInterval(function() {
    $( function() {
      $( function() {
        let data = ''
        let respond = $.get( "/get_best_rate.html", data, success, "json");
      } );
      function success( respond ) {
        let lowest_ask = respond.lowest_ask
        let highest_bid = respond.highest_bid;
        let latestLabel = respond.time;
        let l_ask_stack = respond.l_ask_stack;
        let h_bid_stack = respond.h_bid_stack;
        let spread = respond.spread;
        myLiveChart.addData([highest_bid,lowest_ask], latestLabel);
        document.getElementById("time").value = `${date}, ${latestLabel}`;
        document.getElementById("lowest_ask").value = `${lowest_ask} (${l_ask_stack})`;
        document.getElementById("highest_bid").value = `${highest_bid} (${h_bid_stack})`;
        document.getElementById("spread").value = `\$${spread}`;
        myLiveChart.removeData();
        }
      } )
    }, 60000);
    
  }
</script>


  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li><a href="..">Home</a></li>
          <li><a href="../contact">Contact form</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Content -->
  <div class="container wrapper">
    <div class="container">
      
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">USD to BTC exchange rate graph
            <small>(updated once a minute)</small>
          </h1>
        </div>
      </div>
      
      <div class="row">
        <div id="legend" class="container col-md-3 label-box"">
        </div>
        <div class="container col-md-9">
          <p>The graph shows the highest bid and lowest ask (excluding fee) among the following exchanges: EXMO, Yobit, HitBTC, BitFinex, cCEX, XBTCE, CEX.io, Btc-e.</p>
          <p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-10">
          <canvas id="updating-chart" style="width: 975px; height: 468px;padding-right: 12px">
          </canvas>
        </div>
        <div id="latest_data" class="col-md-2">
        
          <h4>Latest data</h4>
          <b>Time:</b>
            <input id="time" type="text" class="form-control" readonly="true"></input>
          <b>Highest bid:</b>
            <input id="highest_bid" type="text" class="form-control" readonly="true"></input>
          <b>Lowest ask:</b>
            <input id="lowest_ask" type="text" class="form-control" readonly="true"></input>
          <b>Spread:</b>
            <input id="spread" type="text" class="form-control" readonly="true"></input>
        </div>
      </div>

    </div>
  </div>


  <footer style="background-color: #333333;" class="section-inverse">
    <div class="container"> 
      <div class="row copyright">
        <div class="col-md-6">
        <p>&copy;2017 Loutique</p>
        </div>
        <div class="col-md-6">
        <p class="credit">Template by <a href="http://bootstrapious.com/landing-pages">Bootstrapious &mdash; Bootstrap Landing Pages</a></p>
        <!-- Please do not remove the backlink to us. It is part of the licence conditions. Thanks for understanding :)-->
        </div>
      </div>
    </div>
  </footer>
  


<!-- jQuery -->
<script src="/static/js/jquery-1.11.0.min.js"></script>
<script src="/static/js/exchange.js"></script>
<script src="/static/js/bootbox.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/static/js/bootstrap.min.js"></script>

</body>
</html>

myapp/templates/contact.html
<!DOCTYPE html>
<head>

  <link rel="shortcut icon" type="image/png" href="/static/img/favicon.ico"/>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="maze_generator">
  <meta name="author" content="lapantonina">
  
  <title>Maze</title>
  
  <!-- Bootstrap Core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="/static/css/custom.css" rel="stylesheet">

</head>

<body data-spy="scroll" data-target="#navigation" data-offset="120">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li><a href="..">Home</a></li>
          <li><a href="">Contact form</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Content -->
  
  <div class="container wrapper">
    <div class="container">
      {% block contactform %}
          <form action="contact_view" method="post">
              {% csrf_token %}
            {#    {% bootstrap_form form %}#}
              {{ form.non_field_errors }}
            <div>
              <label for="id_subject">Theme:</label>
              {{ form.subject.errors }}
              {#    {{ form.subject }}#}
                <input class="form-control" id="id_subject" name="subject" placeholder="Theme">
            </div>
              &nbsp;
            <div>
              <label for="id_sender">Your e-mail:</label>
              {{ form.sender.errors }}
              {#    {{ form.sender }}#}
                <input class="form-control" id="id_sender" name="sender" placeholder="Your e-mail">
            </div>
              &nbsp;
            <div>
              <label for="id_message">Message:</label>
              {{ form.message.errors }}
              {#    {{ form.message }}#}
                <textarea class="form-control" id="id_message" name="message" placeholder="Input your message"></textarea>
            </div>
              <br>
            <input type="submit" class="btn btn-primary" value="Send"/>
          </form>
      {% endblock %}
    </div>
  </div>

  <footer style="background-color: #333333;" class="section-inverse">
    <div class="container"> 
      <div class="row copyright">
        <div class="col-md-6">
        <p>&copy;2017 Loutique</p>
        </div>
        <div class="col-md-6">
        <p class="credit">Template by <a href="http://bootstrapious.com/landing-pages">Bootstrapious &mdash; Bootstrap Landing Pages</a></p>
        <!-- Please do not remove the backlink to us. It is part of the licence conditions. Thanks for understanding :)-->
        </div>
      </div>
    </div>
  </footer>
  


  <!-- jQuery -->
  <!-- jQuery -->
  <script src="/static/js/jquery-1.11.0.min.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="/static/js/bootstrap.min.js"></script>

</body>
</html>

myapp/templates/mail_sent.html
<!DOCTYPE html>
<head>

  <link rel="shortcut icon" type="image/png" href="/static/img/favicon.ico"/>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="maze_generator">
  <meta name="author" content="lapantonina">
  
  <title>Contact form</title>
  
  <!-- Bootstrap Core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="/static/css/custom.css" rel="stylesheet">

</head>

<body data-spy="scroll" data-target="#navigation" data-offset="120">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li><a href="..">Home</a></li>
          <li><a href="">Contact form</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Content -->
  
  <div class="container wrapper">
    <div class="container">
      <p>The message has been sent successfully</p>
      {% block contactform %}
          <form action="contact_view" method="post">
              {% csrf_token %}
            {#    {% bootstrap_form form %}#}
              {{ form.non_field_errors }}
            <div>
              <label for="id_subject">Theme:</label>
              {{ form.subject.errors }}
              {#    {{ form.subject }}#}
                <input class="form-control" id="id_subject" name="subject" placeholder="Theme">
            </div>
              &nbsp;
            <div>
              <label for="id_sender">Your e-mail:</label>
              {{ form.sender.errors }}
              {#    {{ form.sender }}#}
                <input class="form-control" id="id_sender" name="sender" placeholder="Your e-mail">
            </div>
              &nbsp;
            <div>
              <label for="id_message">Message:</label>
              {{ form.message.errors }}
              {#    {{ form.message }}#}
                <textarea class="form-control" id="id_message" name="message" placeholder="Input your message"></textarea>
            </div>
              <br>
            <input type="submit" class="btn btn-primary" value="Send"/>
          </form>
      {% endblock %}
    </div>
  </div>

  <footer style="background-color: #333333;" class="section-inverse">
    <div class="container"> 
      <div class="row copyright">
        <div class="col-md-6">
        <p>&copy;2017 Loutique</p>
        </div>
        <div class="col-md-6">
        <p class="credit">Template by <a href="http://bootstrapious.com/landing-pages">Bootstrapious &mdash; Bootstrap Landing Pages</a></p>
        <!-- Please do not remove the backlink to us. It is part of the licence conditions. Thanks for understanding :)-->
        </div>
      </div>
    </div>
  </footer>
  


  <!-- jQuery -->
  <!-- jQuery -->
  <script src="/static/js/jquery-1.11.0.min.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="/static/js/bootstrap.min.js"></script>

</body>
</html>

myapp/templates/maze_templ.html
<!DOCTYPE html>
<head>

  <link rel="shortcut icon" type="image/png" href="/static/img/favicon.ico"/>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="maze_generator">
  <meta name="author" content="lapantonina">
  
  <title>Maze</title>
  
  <!-- Bootstrap Core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="/static/css/custom.css" rel="stylesheet">

</head>

<body data-spy="scroll" data-target="#navigation" data-offset="120">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <ul class="nav navbar-nav">
          <li><a href="..">Home</a></li>
          <li><a href="../contact">Contact form</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Content -->
  <div class="container wrapper">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p class="lead">Here is your maze! Size: {{ height }}x{{ width }}. Use arrows to move.
          <form action="/maze" method="get">{% csrf_token %}
            <b>Choose new maze size (HxW):</b>
            <input type="number" class="form-control bfh-number maze-size" name="h" min="1" max="100" required="True"> x <input type="number" class="form-control bfh-number maze-size" name="w" min="1" max="100" required="True">  <input type="submit" class="btn btn-primary" value="Change"></p>
          </form>
          
          <div class="checkbox">
            <label><input id="tracking" type="checkbox">Use tracking</label>
          </div>
          {% autoescape off %}
          {{ runner }}
          {{ gif }}
          {% endautoescape %}
        </div>
      </div>
    </div>
  </div>

  <footer style="background-color: #333333;" class="section-inverse">
    <div class="container"> 
      <div class="row copyright">
        <div class="col-md-6">
        <p>&copy;2017 Loutique</p>
        </div>
        <div class="col-md-6">
        <p class="credit">Template by <a href="http://bootstrapious.com/landing-pages">Bootstrapious &mdash; Bootstrap Landing Pages</a></p>
        <!-- Please do not remove the backlink to us. It is part of the licence conditions. Thanks for understanding :)-->
        </div>
      </div>
    </div>
  </footer>
  


  <!-- jQuery -->
  <script src="/static/js/jquery-1.11.0.min.js"></script>
  <script src="/static/js/maze.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="/static/js/bootstrap.min.js"></script>

</body>
</html>